baseURL = 'https://valignatev.com/'
title = 'The most credible computer media since 1812'
MetaDataFormat = 'toml'
disableKinds = ['sitemap', 'RSS']

[[params.social]]
name = 'twitter'
link = 'https://twitter.com/valignatev'
[[params.social]]
name = 'github'
link = 'https://github.com/valignatev'
[[params.social]]
name = 'stackoverflow'
link = 'https://stackoverflow.com/users/3606603/valignatev'
[[params.social]]
name = 'youtube'
link = 'https://www.youtube.com/channel/UCg0V1MkdYkMlwZPU3IuKLMg'
[[params.social]]
name = 'twitch'
link = 'https://twitch.tv/valignatev'
[[params.social]]
name = 'reddit'
link = 'https://reddit.com/user/valignatev'
