baseURL = 'https://valignatev.com/'
title = 'The most credible computer media since 1812'
MetaDataFormat = 'toml'
enableRobotsTXT = true
disqusShortname = 'valignatev'
enableGitInfo = true
pygmentsUseClasses=true
pygmentsCodeFences=true
[blackfriday]
hrefTargetBlank = true
smartypants = false

[taxonomies]

[sitemap]
changefreq = 'weekly'
filename = 'sitemap.xml'

[author]
email = 'valentignatev@gmail.com'
name = 'Valentin Ignatev'

[[params.social]]
name = 'twitter'
link = 'https://twitter.com/valignatev'
[[params.social]]
name = 'github'
link = 'https://github.com/valignatev'
[[params.social]]
name = 'stackoverflow'
link = 'https://stackoverflow.com/users/3606603/valignatev'
[[params.social]]
name = 'youtube'
link = 'https://www.youtube.com/channel/UCg0V1MkdYkMlwZPU3IuKLMg'
[[params.social]]
name = 'twitch'
link = 'https://twitch.tv/valignatev'
[[params.social]]
name = 'reddit'
link = 'https://reddit.com/user/valignatev'
[[params.social]]
name = 'email'
link = 'mailto:valentignatev@gmail.com'
